# Generated by Django 5.0.2 on 2024-03-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home',
            fields=[
                ('id_home', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.TextField()),
            ],
        ),
    ]
