# Generated by Django 5.0.2 on 2024-03-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_tintas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tintas',
            fields=[
                ('id_tintas', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.TextField(max_length=255)),
                ('modelo', models.TextField(max_length=255)),
                ('ano', models.TextField(max_length=255)),
                ('codigo', models.TextField(max_length=255)),
                ('cor', models.TextField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='home',
        ),
    ]
