# Generated by Django 5.0.2 on 2024-03-06 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_tintas', '0002_tintas_delete_home'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tintas',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
