# Generated by Django 5.0.2 on 2024-03-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cad_tintas', '0003_alter_tintas_ano'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='tintas',
            new_name='tinta',
        ),
    ]
